### PR TITLE
Use Shipping method for Country when Shipping method for State is missing

### PR DESCRIPTION
**Pull request by vnathalye**
Code changes related to:

Shipping rate calculation for different regions
https://wordpress.org/support/topic/shipping-rate-calculation-for-different-regions/

### CODE REVIEW

**Comment by khokandc** [comment]
@vnathalye sorry for late reply. We got your point and thanks for the patch. Your patch working for your required flow but it can be more well structure and can be achieve by hooks / filters. If you have time you can work on the update. We also take care this issue.

**Comment by vnathalye** [comment]
I've removed earlier logic and added following single line now:

$shipping_methods = apply_filters('wcmp_get_shipping_methods_for_shipping_address', $shipping_methods, $package );

This way the existing functionality will not change and I'll still be able to implement my own logic.

I hope you won't have any problem in merging this code change now :)

**Comment by vnathalye** [comment]
@khokandc Did you get a chance to check this?

**Comment by khokandc** [comment]
You can use this `apply_filters('wcmp_get_shipping_methods_for_shipping_address', $shipping_methods, $package ); `for now, we will add this support in our next update.

However, we are looking into better solution for this.

**Pull request closed without merging**
